name: Write__Adapt__
title: WriteAdapt - For People Who Love Content
org: Strategy Media
author: The Octocat
author_url: https://github.com/octocat
base_url: ''
ctx_path: ''
interpolate: false
haml:
  :ugly: true
asciidoctor:
  :safe: safe
  :attributes:
    sitename: WriteAdapt
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
profiles:
  development:
    deploy: nil 
  production:
    base_url: http://lightguard.github.io/writeadapt-lightguard
    ctx_path: /writeadapt-lightguard
    asciidoctor:
      :attributes:
        base_url: http://lightguard.github.io/writeadapt-lightguard
        ctx_path: /writeadapt-lightguard
        imagesdir: http://lightguard.github.io/writeadapt-lightguard/images 
    deploy:
      host: github_pages
      branch: gh-pages
